import { spawn } from 'child_process';
import { join } from 'path';
import * as fs from 'fs';

function callMcpTool(scriptPath: string, toolName: string, args: any): Promise<any> {
  return new Promise((resolve, reject) => {
    console.log(`\nCalling Tool: ${toolName}...`);
    const child = spawn('bun', ['run', scriptPath], {
      stdio: ['pipe', 'pipe', 'pipe']
    });

    let stdoutData = '';
    let stderrData = '';

    child.stdout.on('data', (data) => { stdoutData += data.toString(); });
    child.stderr.on('data', (data) => { stderrData += data.toString(); });

    // Step 1: Initialize
    const initMessage = JSON.stringify({
      jsonrpc: "2.0", id: 1, method: "initialize",
      params: { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "test", version: "1.0" } }
    }) + '\n';
    child.stdin.write(initMessage);

    // Wait a bit, then call the tool
    setTimeout(() => {
      const callMessage = JSON.stringify({
        jsonrpc: "2.0", id: 2, method: "tools/call",
        params: { name: toolName, arguments: args }
      }) + '\n';
      child.stdin.write(callMessage);
    }, 500);

    setTimeout(() => {
      child.kill();
      // Parse the response for id: 2
      const lines = stdoutData.split('\n').filter(l => l.trim() !== '');
      for (const line of lines) {
        try {
          const msg = JSON.parse(line);
          if (msg.id === 2) {
            resolve(msg.result);
            return;
          }
        } catch (e) {}
      }
      reject(new Error("No response found for tool call. Stdout: " + stdoutData + "\nStderr: " + stderrData));
    }, 2000);
  });
}

async function run() {
  const officePath = join(__dirname, 'packages/builtin-mcps/office-suite/src/index.ts');
  const tempDir = join(__dirname, 'test-output');
  if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir);

  const testWordPath = join(tempDir, 'test_report.docx');
  const testExcelPath = join(tempDir, 'test_data.xlsx');
  const testPptPath = join(tempDir, 'test_deck.pptx');

  try {
    // 1. Create Word
    const wordRes = await callMcpTool(officePath, 'create_word', {
      file_path: testWordPath,
      text: "Hello World!\nThis is a test document generated by TwoPixel."
    });
    console.log("create_word result:", wordRes?.content?.[0]?.text);

    // 2. Create Excel
    const excelRes = await callMcpTool(officePath, 'create_excel', {
      file_path: testExcelPath,
      sheet_name: "Sales",
      data: JSON.stringify([{ Name: "Alice", Sales: 100 }, { Name: "Bob", Sales: 200 }])
    });
    console.log("create_excel result:", excelRes?.content?.[0]?.text);

    // 3. Create PPT
    const pptRes = await callMcpTool(officePath, 'create_ppt', {
      file_path: testPptPath,
      slides: JSON.stringify([
        { title: "Welcome to TwoPixel", bullets: ["Fast", "Secure", "AI-Powered"] },
        { title: "Next Steps", bullets: ["Step 1", "Step 2"] }
      ])
    });
    console.log("create_ppt result:", pptRes?.content?.[0]?.text);

    console.log("\n✅ All backend generation tests passed!");
    console.log(`Files saved in: ${tempDir}`);
    console.log(fs.readdirSync(tempDir));

  } catch (err) {
    console.error("Test failed:", err);
  }
}

run();